name: TomatoMAP
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - opencv
  - jupyter
  - jupyterlab
  - notebook
  - pyyaml
  - tqdm
  - requests
  - pip:
      - torch>=2.0.0
      - torchvision>=0.15.0
      - ultralytics>=8.0.0
      - detectron2>=0.6
      - opencv-python>=4.8.0
      - numpy>=1.24.0
      - scipy>=1.10.0
      - pillow>=10.0.0
      - matplotlib>=3.7.0
      - tensorboard>=2.12.0
      - hydra-core>=1.3.0
      - omegaconf>=2.3.0
      - fvcore>=0.1.5
      - pycocotools>=2.0.0
      - black>=23.0.0
      - termcolor>=2.0.0
      - tabulate>=0.9.0
