name: TomatoMAP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - pytorch>=2.2
  - torchvision>=0.17
  - torchaudio
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - pillow
  - opencv
  - jupyter
  - jupyterlab
  - notebook
  - pyyaml
  - tqdm
  - requests
  - tensorboard
  - cython
  - ninja
  - pip:
      #- -e ./submodules/ultralytics
      #- -e ./submodules/detectron2
      - fvcore
      - iopath
      - pycocotools
